version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - target: 5432
        published: 9999
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
    env_file: ./.env
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  pgdata:
    driver: local
